weather/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('weatherapp/', include('weatherapp.urls')),
    path('admin/', admin.site.urls),
    url(r'^admin/statuscheck/', include('celerybeat_status.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weatherapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import ScheduleListView, ScheduleDetailView, ScheduleCreateView, ScheduleUpdateView, ScheduleDeleteView

app_name = 'weatherapp'

urlpatterns = [
    path('', ScheduleListView.as_view(), name='home'),
    path('<int:pk>/', ScheduleDetailView.as_view(), name='detail'),
    path('create/', ScheduleCreateView.as_view(), name='create'),
    path('<int:pk>/update/', ScheduleUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', ScheduleDeleteView.as_view(), name='delete')
]

weatherapp/models.py
from django.db import models
from django.core import validators
import datetime
from accounts.models import User

class Schedule(models.Model):

    this_year = int(datetime.date.today().strftime('%Y'))

    time_choices = []
    num = (i for i in range(48))
    for a in range(24):
        time_choices.append((str(next(num)), str(a)+":00"))
        time_choices.append((str(next(num)), str(a)+":30"))

    information_choices = [
        ('0.5', '30分前'), ('1', '1時間前'), ('2', '2時間前'), ('3', '3時間前'),
        ('6', '6時間前'), ('12', '12時間前'), ('24', '24時間前')
    ]

    year = models.IntegerField(default=this_year, validators=[
        validators.MinValueValidator(this_year, message='無効な値です')
        ])
    month = models.IntegerField(default=1, validators=[
        validators.MinValueValidator(1, message='無効な値です'),
        validators.MaxValueValidator(12, message='無効な値です')
        ])
    day = models.IntegerField(default=1, validators=[
        validators.MinValueValidator(1, message='無効な値です'),
        validators.MaxValueValidator(31, message='無効な値です')
        ])
    title = models.CharField(max_length=50)
    detail = models.CharField(max_length=200)
    start = models.CharField(max_length=2, choices=time_choices, default='0')
    end = models.CharField(max_length=2, choices=time_choices, default='1')
    information = models.CharField(max_length=3, choices=information_choices, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_id = models.CharField(max_length=36, blank=True)

    def __str__(self):
        return self.title


class WeatherForecast(models.Model):

    prefecture = models.CharField(max_length=3)
    city = models.CharField(max_length=4)
    how_many_days_latter = models.IntegerField()
    weather = models.CharField(max_length=5)

    def __str__(self):
        return self.city + str(self.how_many_days_latter)

class ProbabilityOfRain(models.Model):

    prefecture = models.CharField(max_length=3)
    city = models.CharField(max_length=4)
    hour = models.CharField(max_length=5)
    prob_rain = models.CharField(max_length=3)
    day = models.IntegerField()

    def __str__(self):
        return self.city + str(self.day) + '(' + self.hour + ')'

weatherapp/forms.py
from django import forms

from .models import Schedule
from accounts.models import User

import datetime
import time


class ScheduleForm(forms.ModelForm):

    this_year = int(datetime.date.today().strftime('%Y'))

    user = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput())
    year = forms.IntegerField(widget=forms.HiddenInput())
    month = forms.IntegerField(widget=forms.HiddenInput())
    day = forms.IntegerField(widget=forms.HiddenInput())

    title = forms.CharField(widget=forms.TextInput(attrs={'size': 50}))
    detail = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Schedule
        exclude = ('task_id',)

weatherapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.db.models import Max
from weather import tasks
from .models import Schedule, WeatherForecast
from .forms import ScheduleForm

from weather.celery import app

import requests
from bs4 import BeautifulSoup
import re
import datetime
from dateutil.relativedelta import relativedelta
import calendar
import uuid
from faker import Faker


class UserMatchMixin(UserPassesTestMixin):

    raise_exception = True

    def test_func(self):
        user = self.request.user
        obj = get_object_or_404(Schedule, id=self.kwargs['pk'])
        return user.pk == obj.user.id or user.is_superuser


class ScheduleListView(ListView):
    model = Schedule
    template_name = 'weatherapp/home.html'
    context_object_name = 'month_schedule'

    def get(self, request, *args, **kwargs):

        self.weekdays = ['月','火','水','木','金','土','日']
        today = datetime.date.today()
        self.current_year = int(today.strftime('%Y'))
        self.current_month = int(today.strftime('%-m'))
        self.current_day = int(today.strftime('%-d'))
        self.days =[]
        td_day = datetime.timedelta(days=1)
        for i in range(8):
             day = today + i*td_day
             day = day.strftime('%-m月%-d日')
             self.days.append(day)

        td_month = relativedelta(months=1)
        if self.request.GET:
            if self.request.GET.get('year'):
                year = self.request.GET.get('year')
            if self.request.GET.get('pre'):
                month = self.request.GET.get('pre')
                year_month = datetime.datetime.strptime(year+'/'+month, '%Y/%m')
                self.indicative_year = int(datetime.datetime.strftime(year_month-td_month, '%Y'))
                self.indicative_month = int(datetime.datetime.strftime(year_month-td_month, '%m'))
            if self.request.GET.get('post'):
                month = request.GET.get('post')
                year_month = datetime.datetime.strptime(year+'/'+month, '%Y/%m')
                self.indicative_year = int(datetime.datetime.strftime(year_month+td_month, '%Y'))
                self.indicative_month = int(datetime.datetime.strftime(year_month+td_month, '%m'))
            if request.GET.get('month'):
                self.indicative_month = int(request.GET.get('month'))
                self.indicative_year = int(year)
            if request.GET.get('day'):
                self.indicative_day = int(request.GET.get('day'))
            else:
                self.indicative_day = 1
        else:
            self.indicative_year = self.current_year
            self.indicative_month = self.current_month
            self.indicative_day = self.current_day

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        #天気予報
        if self.request.user.is_authenticated:
            pref_key = self.request.user.get_prefecture_display()
            city_key = self.request.user.get_city_display()
        else:
            pref_key = '東京'
            city_key = '東京'

        weather_list = WeatherForecast.objects.filter(prefecture=pref_key, city=city_key)
        weather = []
        for i in weather_list:
            weather.append(i.weather)
        todays_weather = weather[0]


        #カレンダー
        ca = calendar.Calendar(firstweekday=0)
        week_list = ca.monthdayscalendar(self.indicative_year, self.indicative_month)

        context.update(
            prefecture=pref_key,
            city=city_key,
            weather=weather,
            todays_weather=todays_weather,
            days=self.days,
            week_list=week_list,
            weekdays=self.weekdays,
            current_year=self.current_year,
            current_month=self.current_month,
            current_day=self.current_day,
            indicative_year=self.indicative_year,
            indicative_month=self.indicative_month,
            indicative_day=self.indicative_day
        )

        return context

    def get_queryset(self):
        queryset = None
        if self.request.user.is_authenticated:
            queryset = Schedule.objects.filter(
                year=self.indicative_year,
                month=self.indicative_month,
                user=self.request.user.id
            )
        return queryset


class ScheduleDetailView(UserMatchMixin, DetailView):
    model= Schedule


class ScheduleCreateView(LoginRequiredMixin, CreateView):
    model = Schedule
    form_class = ScheduleForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse_lazy('weatherapp:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            initial = {
                'year':int(self.request.GET.get('year')),
                'month':int(self.request.GET.get('month')),
                'day':int(self.request.GET.get('day')),
                'user':self.request.user.id
                }

            form = ScheduleForm(initial=initial)
            context['form'] = form
        return context

    def form_valid(self, form):
        messages.success(self.request, '保存しました')
        try:
            information = float(self.request.POST.get('information'))
            user_id = self.request.user.id
            try:
                schedule_id = list(Schedule.objects.all())[-1].id + 1
            except IndexError:
                schedule_id = None

            today = datetime.datetime.now()
            year = self.request.POST.get('year')
            month = self.request.POST.get('month')
            day = self.request.POST.get('day')

            start_index = int(self.request.POST.get('start'))
            start_time = Schedule.time_choices[start_index][1]
            schedule_start = year + month + day + start_time
            schedule_start = datetime.datetime.strptime(schedule_start, '%Y%m%d%H:%M')
            start_delta = schedule_start - today

            end_index = int(self.request.POST.get('end'))
            end_time = Schedule.time_choices[end_index][1]
            schedule_end = year + month + day + end_time
            schedule_end = datetime.datetime.strptime(schedule_end, '%Y%m%d%H:%M')
            end_delta = schedule_end - today
            end_delta = end_delta.days * 24 * 60 * 60 + end_delta.seconds

            if end_delta <= 0:
                delta = 2
                information =None
            else:
                delta = ((start_delta.days * 24) - information) * 60 * 60 + start_delta.seconds
                if delta <= 0:
                    delta = 2

            try:
                if settings.CELERY_TASK_ALWAYS_EAGER:
                    fake = Faker()
                    Faker.seed(8282)
                    task_id = fake.uuid4()
            except AttributeError:
                task_id = str(uuid.uuid4())

            tasks.sender.apply_async(
                kwargs={'user_id':user_id, 'schedule_id':schedule_id, 'information':information},
                countdown=delta,
                task_id=task_id
            )

            tasks.save_task_id.apply_async(
                kwargs={'task_id':task_id, 'schedule_id':schedule_id},
                countdown=1
            )

        except ValueError:
            pass
        return super().form_valid(form)


class ScheduleUpdateView(UserMatchMixin, UpdateView):
    model = Schedule
    form_class = ScheduleForm
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse_lazy('weatherapp:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update'] = True
        return context

    def form_valid(self, form):
        messages.success(self.request, '更新しました')

        try:
            information = float(self.request.POST.get('information'))
            user_id = self.request.user.id
            schedule_id = self.kwargs['pk']

            today = datetime.datetime.now()
            year = self.request.POST.get('year')
            month = self.request.POST.get('month')
            day = self.request.POST.get('day')

            start_index = int(self.request.POST.get('start'))
            start_time = Schedule.time_choices[start_index][1]
            schedule_start = year + month + day + start_time
            schedule_start = datetime.datetime.strptime(schedule_start, '%Y%m%d%H:%M')
            start_delta = schedule_start - today

            end_index = int(self.request.POST.get('end'))
            end_time = Schedule.time_choices[end_index][1]
            schedule_end = year + month + day + end_time
            schedule_end = datetime.datetime.strptime(schedule_end, '%Y%m%d%H:%M')
            end_delta = schedule_end - today
            end_delta = end_delta.days * 24 * 60 * 60 + end_delta.seconds

            if end_delta <= 0:
                delta = 2
                information =None
            else:
                delta = (start_delta.days * 24 - information) * 60 * 60 + start_delta.seconds
                if delta <= 0:
                    delta = 2

            try:
                if settings.CELERY_TASK_ALWAYS_EAGER:
                    fake = Faker()
                    Faker.seed(8282)
                    task_id = fake.uuid4()
            except AttributeError:
                task_id = str(uuid.uuid4())

            tasks.sender.apply_async(
                kwargs={'user_id':user_id, 'schedule_id':schedule_id, 'information':information},
                countdown=delta,
                task_id=task_id

weatherapp/templates/weatherapp/home.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class='row justify-content-start'>
  <h5 class='offset-md-1 offset-0'>今日の<span style='color: red;'>{{ city }}（{{ prefecture }}）</span>の天気：</h5>
  <h5>{{ todays_weather }}</h5>
</div>
<div class='row justify-content-start align-items-center'>
  <div class='week-weather col-xl-6 col-md-10 offset-md-1 offset-0'>
  <div class='table-responsive'>
  <table class='table text-nowrap' width='800' border='1' cellpadding="10">
  <caption style='caption-side: top; font-size:20px; color:orange;'>一週間の天気</caption>

    <thead>
    <tr>
    {% for i in days %}
      <th style='text-align:center;'>{{ i }}</th>
    {% endfor %}
    </tr>
    </thead>

    <tbody>
    <tr>
    {% for i in weather %}
      <td style='text-align:center;'>{{ i }}</td>
    {% endfor %}
    </tr>
    </tbody>

  </table>
  </div>
  </div>
  <div class='month_calendar col-xl-3 offset-md-1 offset-0' height= 600 width=300 sytle='float: left;'>
    <a href="{% url 'weatherapp:home' %}?pre={{ indicative_month }}&year={{ indicative_year }}">　<<　</a>
    <a href='#'>{{ indicative_year }}年{{ indicative_month }}月</a>
    <a href='{% url "weatherapp:home" %}?post={{ indicative_month }}&year={{ indicative_year }}'>　>>　</a>
    <table border="1" width=300 cellspacing="0" cellpadding="5">
      <tr>
      {% for weekday in weekdays %}
        <th height=15>
          {{ weekday }}
        </th>
      {% endfor %}
      </tr>

      {% for week in week_list %}
        <tr>
        {% for day in week %}
          {% if indicative_year == current_year and indicative_month == current_month and day == current_day %}
          <td bgcolor='#ccf8ff' height=30>
          {% else %}
          <td height=30>
          {% endif %}
            {% if day != 0 %}
              <a href="{% url 'weatherapp:home' %}?day={{ day }}&month={{ indicative_month }}&year={{ indicative_year }}">{{ day }}</a>
            {% endif %}
          </td>
        {% endfor %}
        </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br>


<div class='week_calendar row justify-content-start'>
<div class='col-md-10 col-12 offset-md-1 offset-0 table-responsive'>
  <div class='w-100'></div>
  <table class='table text-nowrap' border="1" cellpadding="5">
  <caption style='caption-side:top; font-size:20px; color:orange;'>週間スケジュール</caption>

  <thead>
  <tr>
  {% for weekday in weekdays %}
    <th style='text-align:center;'>
      {{ weekday }}
    </th>
  {% endfor %}
  </tr>
  </thead>

  <tbody>
  {% for week in week_list %}
  <tr>
  {% if indicative_day in week %}
  {% for day in week %}
    <td>
      {% if day != 0 %}
        <p>{{ day }}</p>
        <br>
        {% for schedule in month_schedule %}
        {% if schedule.day == day %}
        <p>{{ schedule.get_start_display }} - {{ schedule.get_end_display }}</p>
        <p class='font-weight-bold'>{{ schedule.title | truncatechars:10 }}</p>
        <a href='{% url "weatherapp:detail" schedule.id %}'>詳細</a>
        <br>
        <br>
        {% endif %}
        {% endfor %}
        <br>
        <br>
          <a class='btn btn-primary' href='{% url "weatherapp:create" %}?day={{ day }}&month={{ indicative_month }}&year={{ indicative_year }}' style='color:white;'>追加</a>
      {% endif %}
    </td>
  {% endfor %}
  {% endif %}
  </tr>
  {% endfor %}
  </tbody>
  </table>
</div>
</div>

{% endblock %}

weatherapp/templates/weatherapp/schedule_confirm_delete.html
{% extends 'base.html' %}
{% block body %}
<h3>削除の確認</h3>
<p>本当に削除してもよろしいですか？</p>
<form method='post'>
  {% csrf_token %}
  {{form}}
  <button class='btn btn-danger' type='submit'>削除</button>
  <a class='btn btn-secondary' href='{% url "weatherapp:home" %}'>キャンセル</a>
</form>
{% endblock %}

weatherapp/templates/weatherapp/schedule_detail.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class='row justify-content-start'>
<table class='col-xl-5 col-lg-8 col-md-10 col-sm-11 col-12 offset-md-1 offset-0'>
  <tr>
    <th class='text-nowrap'><label for="id_title">タイトル：</label></th>
    <td><p id="id_title">{{object.title}}</p></td>
  </tr>
  <tr>
    <th class='text-nowrap'><label for="id_time">時間：</label></th>
    <td><p id="id_time">{{ schedule.get_start_display }} - {{ schedule.get_end_display }}</p></td>
  </tr>
  <tr>
    <th class='text-nowrap'><label for="id_detail">詳細：</label></th>
    <td><p id="id_detail">{{object.detail}}</p></td>
  </tr>
</table>
</div>

<div class='row justify-content-start'>
<div class='offset-md-1 offset-0'>
<a class='btn btn-primary' href='{% url "weatherapp:update" object.id %}'>編集</a>
<a class='btn btn-danger' href='{% url "weatherapp:delete" object.id %}'>削除</a>
</div>
</div>

{% endblock %}

weatherapp/templates/weatherapp/schedule_form.html
{% if update %}
<h3>更新</h3>
{% else %}
<h3>新規作成</h3>
{% endif %}
<form method='post'>
  {% csrf_token %}
  <table>
  {{ form }}
  </table>
  {% if update %}
  <button class='btn btn-primary' type='submit'>反映</button>
  {% else %}
  <button class='btn btn-primary' type='submit'>送信</button>
  {% endif %}


</form>