accounts/urls.py
"""ユーザー登録に関するurls.py"""
from django.urls import path
from accounts.views import SignUpView, SignOutView, UserDetailView, UserUpdateView

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<int:pk>/signout/', SignOutView.as_view(), name='signout'),
    path('<int:pk>/detail/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='update'),
    ]

weather/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('weatherapp/', include('weatherapp.urls')),
    path('admin/', admin.site.urls),
    url(r'^admin/statuscheck/', include('celerybeat_status.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weatherapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import ScheduleListView, ScheduleDetailView, ScheduleCreateView, ScheduleUpdateView, ScheduleDeleteView

app_name = 'weatherapp'

urlpatterns = [
    path('', ScheduleListView.as_view(), name='home'),
    path('<int:pk>/', ScheduleDetailView.as_view(), name='detail'),
    path('create/', ScheduleCreateView.as_view(), name='create'),
    path('<int:pk>/update/', ScheduleUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', ScheduleDeleteView.as_view(), name='delete')
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Weatherapp</title>
  </head>
  <body>
  {% include 'navi.html' %}

  <div class="container-fluid">

  {% if messages %}
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
  <ul style='list-style-type:none;'>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
  {% endif %}
  {% block body %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/navi.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light"  style='background-color:#80eeff'>
  <a href="{% url 'weatherapp:home' %}" class='navbar-brand' style='font-size:30pt; color:white;'>
    <img src='{% static "sun.png" %}' width='50' height='50'>
    Weatherapp
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:detail' user.id %}"  style='color:white; padding:10px;'>{{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"  style='color:white; padding:10px;'>ログアウト</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}" style='color:white; padding:10px;'>ログイン</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}" style='color:white; padding:10px;'>新規登録</a>
        </li>
          {% endif %}
      </ul>
    </div>
</nav>